CREATE TABLE IF NOT EXISTS campaigns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bank TEXT NOT NULL,
  external_id TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  image_url TEXT,
  url TEXT,
  hash TEXT NOT NULL,
  version INTEGER NOT NULL DEFAULT 1,
  first_seen TIMESTAMPTZ NOT NULL,
  last_seen TIMESTAMPTZ NOT NULL,
  last_updated TIMESTAMPTZ NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  UNIQUE (bank, external_id)
);

CREATE INDEX IF NOT EXISTS idx_campaigns_bank ON campaigns (bank);
CREATE INDEX IF NOT EXISTS idx_campaigns_active ON campaigns (is_active);

